package br.com.givemearecipe.controller.recipe;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class RecipeController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private RecipeService recipeService;
	

	
	
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection FindRecipes(Collection ids) {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public Recipe CreateRecipe(Recipe recipe) {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public Recipe GetRecipe(int Id) {
		// FIXME: auto-generated method stub
		return null;
	}
	
}