package br.com.givemearecipe.entity.recipe;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Category extends PersistentObjectSupport implements Comparable<Category> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String name;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToMany(mappedBy="Target")
		private Set<Recipe> Source;
		
	




	/** Getter for name. */
	public String getName() {
		return name;
	}
	
	/** Setter for name. */
	public void setName(String name) {
		this.name = name;
	}




		
		/** Getter for Source. */
		public Set<Recipe> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Recipe> Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Category o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}