package br.com.givemearecipe.entity.recipe;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Portion extends PersistentObjectSupport implements Comparable<Portion> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private float size;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private UnitOfMeasure unit;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne(mappedBy="Target")
		private IngredientContainer Source;
		
	




	/** Getter for size. */
	public float getSize() {
		return size;
	}
	
	/** Setter for size. */
	public void setSize(float size) {
		this.size = size;
	}

	/** Getter for unit. */
	public UnitOfMeasure getUnit() {
		return unit;
	}
	
	/** Setter for unit. */
	public void setUnit(UnitOfMeasure unit) {
		this.unit = unit;
	}




		
		/** Getter for Source. */
		public IngredientContainer getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(IngredientContainer Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Portion o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}