package br.com.givemearecipe.entity.recipe;

/** TODO: generated by FrameWeb. Should be documented. */
public enum UnitOfMeasure {
	centimeter, cup, deciliter, fluid_ounce, gallon, gill, gram, inch, kilogram, liter, meter, milliliter, millimeter
, milligram, ounce, pint, pound, quart, tablespoon, teaspoon, unit;
}